main: me.prisonranksx.PrisonRanksX
version: 2.5.13
name: PrisonRanksX
author: TheGaming999 aka Al3rb
load: POSTWORLD
depend: [Vault]
softdepend: [PlaceholderAPI,MVdWPlaceholderAPI,HolographicDisplays,ActionUtil,PermissionsEX,GroupManager,LuckPerms]