main: me.collincraig.HexiaPrisonRanks
version: 2.5.13
name: HexiaPrisonRanks
author: TheGaming999 (Forked by: HexiaMC DrPuffy)
load: POSTWORLD
depend: [Vault]
softdepend: [PlaceholderAPI,MVdWPlaceholderAPI,HolographicDisplays,ActionUtil,PermissionsEX,GroupManager,LuckPerms]